#!/bin/bash
# GSD: Deploy ThumbGate Control Plane to Google Cloud Run

set -euo pipefail

PROJECT_ID=$(gcloud config get-value project)
SERVICE_NAME="rlhf-control-plane"
REGION="us-central1"

: "${THUMBGATE_API_KEY:?THUMBGATE_API_KEY is required}"
: "${THUMBGATE_API_KEY_ROTATED_AT:?THUMBGATE_API_KEY_ROTATED_AT is required}"
: "${STRIPE_SECRET_KEY:?STRIPE_SECRET_KEY is required}"
: "${STRIPE_SECRET_KEY_ROTATED_AT:?STRIPE_SECRET_KEY_ROTATED_AT is required}"
: "${STRIPE_WEBHOOK_SECRET:?STRIPE_WEBHOOK_SECRET is required}"
: "${STRIPE_WEBHOOK_SECRET_ROTATED_AT:?STRIPE_WEBHOOK_SECRET_ROTATED_AT is required}"
: "${THUMBGATE_PUBLIC_APP_ORIGIN:?THUMBGATE_PUBLIC_APP_ORIGIN is required}"
: "${THUMBGATE_BILLING_API_BASE_URL:?THUMBGATE_BILLING_API_BASE_URL is required}"

THUMBGATE_FEEDBACK_DIR="${THUMBGATE_FEEDBACK_DIR:-/data/feedback}"
THUMBGATE_GA_MEASUREMENT_ID="${THUMBGATE_GA_MEASUREMENT_ID:-}"
THUMBGATE_GOOGLE_SITE_VERIFICATION="${THUMBGATE_GOOGLE_SITE_VERIFICATION:-}"

node scripts/deploy-policy.js --profiles=runtime,billing

echo "🚀 Deploying Agentic Control Plane to $REGION..."

gcloud builds submit --tag gcr.io/$PROJECT_ID/$SERVICE_NAME
gcloud run deploy $SERVICE_NAME \
  --image gcr.io/$PROJECT_ID/$SERVICE_NAME \
  --platform managed \
  --region $REGION \
  --allow-unauthenticated \
  --set-env-vars \
THUMBGATE_API_KEY="$THUMBGATE_API_KEY",\
STRIPE_SECRET_KEY="$STRIPE_SECRET_KEY",\
STRIPE_WEBHOOK_SECRET="$STRIPE_WEBHOOK_SECRET",\
THUMBGATE_PUBLIC_APP_ORIGIN="$THUMBGATE_PUBLIC_APP_ORIGIN",\
THUMBGATE_BILLING_API_BASE_URL="$THUMBGATE_BILLING_API_BASE_URL",\
THUMBGATE_FEEDBACK_DIR="$THUMBGATE_FEEDBACK_DIR",\
THUMBGATE_GA_MEASUREMENT_ID="$THUMBGATE_GA_MEASUREMENT_ID",\
THUMBGATE_GOOGLE_SITE_VERIFICATION="$THUMBGATE_GOOGLE_SITE_VERIFICATION"

echo "✅ Success! Your Control Plane is live."
gcloud run services describe $SERVICE_NAME --region $REGION --format='value(status.url)'
